# Define the module name
set(MODULE_NAME mod_trial_of_finality)

# Specify the source files
set(MODULE_SOURCES
    src/YourSourceFile.cpp
    # Add other source files as needed
)

# Include directories
include_directories(
    ${CMAKE_SOURCE_DIR}/src
    ${CMAKE_SOURCE_DIR}/modules
    # Add other directories as needed
)

# Define the module as a shared library
add_library(${MODULE_NAME} MODULE ${MODULE_SOURCES})

# Link against necessary libraries
target_link_libraries(${MODULE_NAME}
    AzerothCore
    # Add other libraries as needed
)

# Set the output directory for the module
set_target_properties(${MODULE_NAME} PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/modules/${MODULE_NAME}/
)
