name: Build AzerothCore with My Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mod repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake make gcc g++ libssl-dev libmysqlclient-dev mysql-client

      - name: Clone AzerothCore
        run: |
          git clone --depth=1 https://github.com/azerothcore/azerothcore-wotlk.git azerothcore
          mkdir azerothcore/modules
          cp -r $GITHUB_WORKSPACE azerothcore/modules/my-mod

      - name: Build AzerothCore + mod
        run: |
          cd azerothcore
          mkdir build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=../bin
          make -j$(nproc)

      - name: Check if worldserver binary exists
        run: |
          test -f azerothcore/bin/bin/worldserver && echo "Build successful" || (echo "Build failed" && exit 1)
